FROM debian as openssl-build

RUN apt update && apt install -y git zlib1g-dev make gcc

WORKDIR /openssl

RUN git clone https://github.com/openssl/openssl.git ./ \
    && git checkout OpenSSL_1_1_1-stable

RUN ./config --prefix=/usr/local --openssldir=/usr/local/lib/ssl \
    -DOPENSSL_USE_BUILD_DATE -DOPENSSL_USE_IPV6 -static \
    enable-weak-ssl-ciphers

    # docker run test ciphers -V 'ALL:COMPLEMENTOFALL' > test && ./check.sh | grep -V SSLv2
    
RUN make -j $(nproc) depend

RUN make -j $(nproc)

RUN make install

FROM debian

COPY --from=openssl-build /usr/local/bin/openssl /usr/local/bin/
COPY --from=openssl-build /usr/local/lib/ssl /usr/local/lib/ssl
COPY --from=openssl-build /usr/local/include/openssl /usr/local/include/openssl

ENTRYPOINT ["/usr/local/bin/openssl"]
