name: build openssl docker image

on:
  push:
    paths:
    - "**Dockerfile**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Docker Build, Tag, Push
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Tag, Push
        uses: mattdavis0351/actions/docker-gpr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: openssl:1.0.2-chacha